[project]
name = "rl-2048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "gymnasium==1.1.1",
    "keras==3.9.2",
    "tensorflow==2.19.0",
    "tensorflow[and-cuda]>=2.19.0 ; sys_platform == 'linux'",
]


[tool.black]
line-length = 100
target-version = ['py312']


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
